llm:
  provider: openai
  config:
    model: 'open-hermes-2.5'
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false
    prompt: |
      Use the following pieces of context to answer the query at the end.
      If you don't know the answer, just say that you don't know, don't try to make up an answer.

      $context

      Query: $query

      Helpful Answer:
    system_prompt: |
      Answer the following questions in the style of a pirate, matey!.

embedder:
  provider: huggingface
  config:
    model: 'BAAI/bge-large-en-v1.5'

vectordb:
  provider: chroma
  config:
    collection_name: 'my-collection'
    dir: db
    allow_reset: true
